#!/bin/sh
export PATH=/usr/local/bin:$PATH
echo "\n-----------------------------------------------------------------------------------------------------------------------------------\n"
PASS=true
echo "\nValidating Javascript:\n"
# Check for eslint
which eslint &> /dev/null
npm run lint
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi

echo "\nJavascript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
